### ISSUE TITLE
Important question regarding api and teamlearn website

### ISSUE THREAD

**Issue by SaptakBhoumik** [teamlearncoding/teamlearn#12]
The system that checks if the code works perfectly or not is not affective so I was thinking of using an api key but if I just put the api key directly in the code then many people can misuse it but if I don't put the api key in the code then it will be difficult for the developer to set up the api key. The decision is up to you whether you want to expose the key or not. Btw go to https://www.jdoodle.com/ and create an api key and send it to me via email. This api key will help to validate the code

**Comment by koreaneggroll** [comment]
Idk man. Im sorry for responding so late. The api is basically just a learning experience for me rn.
