### ISSUE TITLE
We need experienced css devs

### ISSUE THREAD

**Issue by koreaneggroll** [teamlearncoding/teamlearn#5]
Well the ui is really bad right now and we need css devs to help us make it better

**Comment by Keshav25** [comment]
I could potentially help, do you already have a mockup of what you want the site to look like?

**Comment by koreaneggroll** [comment]
No actually. I'm really really really bad at designing, even if I would come up with something it would be horrible. If i'm not being an ***hole could you design it with what's already there?

**Comment by Keshav25** [comment]
Sure, I'll start working on the UI soon. Probably tomorrow after I get off work

**Comment by koreaneggroll** [comment]
you're the best. thanks a lot

**Comment by SaptakBhoumik** [comment]
@koreaneggroll I can help

**Comment by koreaneggroll** [comment]
@SaptakBhoumik if u want to go ahead

**Comment by SaptakBhoumik** [comment]
Ok

**Comment by SaptakBhoumik** [comment]
Give me a week

**Comment by SaptakBhoumik** [comment]
![image](https://user-images.githubusercontent.com/74509281/116875837-2f344480-ac39-11eb-8165-78e39a42020c.png)
Do you want to add anything else to the text

**Comment by SaptakBhoumik** [comment]
My frontend is almost ready

**Comment by MrGithub2021** [comment]
Let's close this.
